# Generated by Django 3.1.1 on 2020-09-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0006_survey_exit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
