# Generated by Django 3.1.1 on 2020-09-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0007_auto_20200923_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='update_time',
            new_name='enter_time',
        ),
    ]
