# Generated by Django 3.1.1 on 2020-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0008_auto_20200923_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='graph_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='enter_time',
            field=models.DateTimeField(),
        ),
    ]
