# Generated by Django 3.0.6 on 2020-10-25 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0009_auto_20201008_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph_survey',
            name='name',
        ),
    ]
